name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Run lint
        run: ./gradlew lint

      - name: Run unit tests
        run: ./gradlew test -- stacktrace

      - name: Build release
        run: ./gradlew build

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: app/build/outputs/apk/debug/app-release.apk









